name: CI

on: [push]

jobs:

  build-win:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: |
        python -m venv venv
        . .\venv\Scripts\activate.ps1
        pip install -r requirements.txt

    - name: Build
      run: |
        . .\venv\Scripts\activate.ps1
        fbs freeze
        Compress-Archive -Path "target\Vial" -DestinationPath vial-win.zip

    - uses: actions/upload-artifact@v4
      with:
        name: vial-win
        path: vial-win.zip
